### ISSUE TITLE
Authentication is broken both in Heroku and localhost

### ISSUE THREAD

**Issue by BingyanZen** [blanksblanks/project-cookie#23] opened 2015-02-28 19:37 UTC

**Comment by blanksblanks** [comment] 2015-02-28 19:43
http://project-cookie.herokuapp.com/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

in addition, heroku keeps shutting down. if we can't get logged in, we can't work on the other gitRepos pages and can only work on the main index.html page.

![image](http://cl.ly/image/2j1z1b0W402K/Image%202015-02-28%20at%202.40.59%20PM.png)

**Comment by blanksblanks** [comment] 2015-02-28 21:06
After looking more into it appears to be a Redirect URI mismatch: https://developer.github.com/v3/oauth/#common-errors-for-the-authorization-request

@ozzieba looks like you need to check out your OAuth application  in Github Settings and check out the authorixation callback url?

**Comment by ozzieba** [comment] 2015-02-28 23:43
So sorry about this, it worked for me yesterday, and it seems to be working now, and I was unable to look at it in between.
Did you guys figure it out?

**Comment by jzf2101** [comment] 2015-02-28 23:44
Not exactly wed love your help

On Feb 28, 2015, at 18:44, ozzieba notifications@github.com wrote:

So sorry about this, it worked for me yesterday, and it seems to be working
now, and I was unable to look at it in between.
Did you guys figure it out?

**Comment by ozzieba** [comment] 2015-02-28 23:47
Can you tell me exactly what is going on?
Are you guys on campus, should I join you?

**Comment by blanksblanks** [comment] 2015-03-01 00:14
@jzf2101 I thought you fixed the problem? By changing to your own GitHub dev token and changing some of the post/get/other things GitHub OAuth specifically wants?
@ozzieba I just got home! But if you're free next weekend or Friday that would be great. I have AP midterm Thursday so might not be the freest. The problem with logging into github appeared in three forms: a) we clicked login and all we got was the 2014 footer with the redirect uri error, b) clicked login and got username and password fields for github but got the 2014 footer with the redirect uri error when we submitted the information and c) heroku server would go down and show that Application Error you saw above.
However, when Jessica arrived she actually managed to log in. Bingyan and I tried clearing our cache and visiting the site from incognito and we mainly got problem type b as described above. Not sure what's going on but we'll try to work on the page view for now though we really need to figure out this authentication thing and how to get some meaningful data for the graph visualization.

**Comment by jzf2101** [comment] 2015-03-01 00:18
I didn't the changes I made only work on the version that's local not when
it's transferred to heroku

On Feb 28, 2015, at 19:14, Nina Baculinao notifications@github.com wrote:

@jzf2101 https://github.com/jzf2101 I thought you fixed the problem? By
changing to your own GitHub dev token and changing some of the
post/get/other things GitHub OAuth specifically wants?
@ozzieba https://github.com/ozzieba I just got home! But if you're free
next weekend or Friday that would be great. I have AP midterm Thursday so
might not be the freest. The problem with logging into github appeared in
three forms: a) we clicked login and all we got was the 2014 footer with
the redirect uri error, b) clicked login and got username and password
fields for github but got the 2014 footer with the redirect uri error when
we submitted the information and c) heroku server would go down and show
that Application Error you saw above.
However, when Jessica arrived she actually managed to log in. Bingyan and I
tried clearing our cache and visiting the site from incognito and we mainly
got problem type b as described above. Not sure what's going on but we'll
try to work on the page view for now though we really need to figure out
this authentication thing and how to get some meaningful data for the graph
visualization.

**Comment by ozzieba** [comment] 2015-03-01 00:26
OK, I will troubleshoot and keep you updated

**Comment by ozzieba** [comment] 2015-03-02 05:39
Should be working now, with commit 15df0ca55b0742c9ba687ad38b521b5cd2d195cf

**Comment by jzf2101** [comment] 2015-03-02 16:46
@ozzieba Mine doesn't run on local host:

![screen shot 2015-03-02 at 11 45 34](https://cloud.githubusercontent.com/assets/1373035/6445418/b1a7e2f0-c0d1-11e4-8189-7a0f17f3af8d.png)

**Comment by ozzieba** [comment] 2015-03-02 16:48
localhost is more problematic,  but should work if you use the previous
.env file, with an API key that points to localhost

**Comment by jzf2101** [comment] 2015-03-02 16:50
We need to be able to run this locally for development purposes.  @levbrie said we could edit the key's settings in github to allow for various callback URIs.

**Comment by ozzieba** [comment] 2015-03-02 17:26
As far as I can tell there is only space for one redirect URI.
I am looking at https://github.com/organizations/project-cookie/settings/applications/173520
You should be able to access that as an owner of the project-cookie organization, which owns the app. Feel free to add localhost if you find a way, or just replace Heroku with localhost if you think that's better.

**Comment by ozzieba** [comment] 2015-03-02 17:27
Actually @jzf2101 you are not yet an owner, you need to accept the invitation first

**Comment by ozzieba** [comment] 2015-03-02 17:30
Alternatively,  we can add a second App with its own clientId and secret that points to localhost, and then change .env and the config files to use that

**Comment by ozzieba** [comment] 2015-03-02 17:34
Though I would recommend against putting .env with GITHUB_SECRET on GitHub, then anyone can theoretically put a random app on their localhost that uses our account...

**Comment by ozzieba** [comment] 2015-03-02 17:35
Also, @jzf2101, can you confirm that it works for you on Heroku?

**Comment by jzf2101** [comment] 2015-03-02 18:09
@ozzieba  it works on heroku.  I think @levbrie also mentioned the possibility of having multiple keys depending on if its running locally or on heroku.

**Comment by blanksblanks** [comment] 2015-03-02 19:46
@ozzieba doesn't work for me on heroku, i still get: http://project-cookie.herokuapp.com/?error=redirect_uri_mismatch&error_description=The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application.&error_uri=https:%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

**Comment by jzf2101** [comment] 2015-03-02 19:49
Can we talk about it Wednesday?

On Mar 2, 2015, at 14:46, Nina Baculinao notifications@github.com wrote:

@ozzieba https://github.com/ozzieba doesn't work for me on heroku, i
still get:
http://project-cookie.herokuapp.com/?error=redirect_uri_mismatch&error_description=The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application.&error_uri=https:%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

**Comment by ozzieba** [comment] 2015-03-02 19:59
Sorry, I am currently working on getting it to work on both Heroku and localhost, accidentally put the wrong key on Heroku, both should be working soon

**Comment by ozzieba** [comment] 2015-03-02 20:13
@blanksblanks Can you try again now with Heroku?

**Comment by ozzieba** [comment] 2015-03-02 21:01
As far as I can tell it is working on both localhost and Heroku. Please try it out and let me know what the results are.
Essentially the clientId (which is not super-secret) is stored in the code, and the app chooses the 'localhost' one if that is the URI. The github client secret is stored in the .env file, which is not on GitHub for security reasons. The .env file contains the client secret for the localhost version (https://github.com/organizations/project-cookie/settings/applications/174891), while the a separate .distenv file (also not on GitHub) contains the client secret for the Heroku version (https://github.com/organizations/project-cookie/settings/applications/173520). 
Running 'grunt build' creates a minified version of the app in dist for Heroku, and it copies .distenv to dist/.env. To create those files, you can fill in the relevant fields in .envtemplate, or use heroku toolbelt and run (from some empty directory) heroku clone --app project-cookie && cd project-cookie&&heroku config:pull, and just replace the github secret with the localhost value

**Comment by jzf2101** [comment] 2015-03-03 15:47
@ozzieba I can't log in anymore.  Could we meet tomorrow to work this out with @levbrie ?

**Comment by ozzieba** [comment] 2015-03-03 16:37
I'm having trouble reproducing the error you got, but I'm trying to fix it. 
From the Heroku logs it seems the browser is requesting /api/users/me, thinking it's authenticated, but the user was not found on the server, probably because I cleared the user database to get a fresh start (some of the user entries were broken with bad authentication tokens, and I wanted to make sure it was able to get the GitHub tokens from scratch when they were not in the database). You should be able to avoid this by getting a fresh browser session, eg chrome incognito mode or clearing all browser cache for the site. 
I've also added a couple lines that should gracefully handle the situation without causing the server to die.
Aside from that, if you get a chance to test the localhost version and let me know what happens, that would be useful. Let me know if you need help setting up the .env file.

**Comment by jzf2101** [comment] 2015-03-03 16:47
Ok- could you try documenting what you're doing? I'm really confused by the
directory structure changes youve been making

On Mar 3, 2015, at 11:37, ozzieba notifications@github.com wrote:

I'm having trouble reproducing the error you got, but I'm trying to fix it.
From the Heroku logs it seems the browser is requesting /api/users/me,
thinking it's authenticated, but the user was not found on the server,
probably because I cleared the user database to get a fresh start (some of
the user entries were broken with bad authentication tokens, and I wanted
to make sure it was able to get the GitHub tokens from scratch when they
were not in the database). You should be able to avoid this by getting a
fresh browser session, eg chrome incognito mode or clearing all browser
cache for the site.
I've also added a couple lines that should gracefully handle the situation
without causing the server to die.
Aside from that, if you get a chance to test the localhost version and let
me know what happens, that would be useful. Let me know if you need help
setting up the .env file.

**Comment by ozzieba** [comment] 2015-03-03 17:02
As noted in my previous message, I changed precisely two lines.
The last time I've re-arranged the directory structure in any way was 2/27. The changes I made included adding 'github' directories to the 'server' and 'public/app' directories, removing the unused 'http-angular' directory, and moving everything from the col-ang-gen directory to the root of the project. I tried to explain that in my explanation of the github module and the commit logs, but I may not have been too clear.
Can you elaborate on what is confusing, so I can try to explain it better?
I do truly apologize if my documentation / communication skills are lacking, I have relatively little experience with these types of collaborative projects.

**Comment by ozzieba** [comment] 2015-03-04 18:06
This is now working on both localhost and Heroku, tested by Cheng, Jessica, and myself. Make sure to download the .env file from your email (3/3 12:14PM) and put it in the root of the project. Also note a reload is required for the current commit on the master branch (fixed on oz-dev branch) Will re-open if there are issues again.

**Closed as completed by ozzieba** 2015-03-04 18:06 UTC
Labels: bug
