### ISSUE TITLE
Get routing setup for a new module

### ISSUE THREAD

**Issue by blanksblanks** [blanksblanks/project-cookie#22] opened 2015-02-25 21:10 UTC
@ozzieba, @levbrie said that he will be pushing the major changes to the columbia generator soon, so if we've already started the project we can look at his recent commits and how he created the issues module to get an overall picture of how to connect a new module view controller to the page.

you've done a lot for the project already, so if you need help, let us know how we can help! keep us updated!

**Comment by blanksblanks** [comment] 2015-02-25 21:19
Oops didn't mean to assign you the task, I just wanted to tag your name in the comment! This is probably the part we will focus on on Saturday

**Comment by ozzieba** [comment] 2015-02-27 16:46
commit 106790f014c8574d000f6f609ef801ab03dd94d9 gives a bare-bones git module.
Here is what I did:
- public/app/layoutmain.html is the file that shows "Content". I added a <git-info></git-info> line
- that line is seen by Angular (on the client), which calls app/github/gitInfo.js 
- gitInfo.js defines the git-info directive, assigns it a controller (gitCtrl) and a template html file app/github/git.html
- git.html simply includes the line {{gitRepos}}
- gitCtrl.js maps gitRepos to GithubService.getRepos
- GithubService.js defines getRepos(), which queries the server at address '/repos'
- server/config/routes.js (running on Node) redirects the '/route' request to server/github/index.js
- server/github/index.js routes the request first to authService.ensureAuthenticated, then to gitController.repos
- server/github/gitController.js defines the repos function, which actually queries the Github server based on the authorization token we have for the user, and returns the repos data
Now the data is returned to the client-side gitCtrl.getRepos(), and Angular replaces the {{gitRepos}} line with the result

**Comment by ozzieba** [comment] 2015-02-27 16:59
Since I'm pretty sure comment-edits don't generate email notifications, here is a new description with typo fixes etc:
commit 106790f014c8574d000f6f609ef801ab03dd94d9 gives a bare-bones git module.
Here is what I did:
- public/app/layout/main.html is the file that shows "Content". I added a `<git-info></git-info>` line
- that line is seen by Angular (on the client), which calls app/github/gitInfo.js 
- gitInfo.js defines the git-info directive, assigns it a controller (gitCtrl) and a template html file app/github/git.html. This means that our git-info directive is replaced with the contents of git.html
- git.html simply includes the line {{gitRepos}}
- gitCtrl.js maps gitRepos to GithubService.getRepos
- GithubService.js defines getRepos(), which queries the server at address '/repos'
- server/config/routes.js (running on Node) redirects the '/repos' request to server/github/index.js
- server/github/index.js routes the request first to authService.ensureAuthenticated, then to gitController.repos
- server/github/gitController.js defines the repos function, which actually queries the Github server based on the authorization token we have for the user, and returns the repos data
  Now the data is returned to the client-side gitCtrl.getRepos(), and Angular replaces the {{gitRepos}} line with the result

Let me know what you think, hopefully this should help you make improvements tomorrow

**Comment by blanksblanks** [comment] 2015-03-01 00:35
Usefully illustrates how Lev built up the issues in http://columbiajs-issue-tracker.herokuapp.com/

https://github.com/ColumbiaJS/issue-tracker/compare/c35634a...291f3f0?diff=split&name=291f3f0

**Comment by ozzieba** [comment] 2015-03-04 18:09
This is done properly in the oz-dev branch. I would like to merge that to master as soon as everyone has confirmed that it works. I will close this issue after that happens and I improve the docs

**Closed as completed** 2015-03-08 00:22 UTC
Labels: feature
